# Generated by Django 3.2.13 on 2022-06-30 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InformeMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField(verbose_name='Mes')),
                ('año', models.IntegerField(verbose_name='Año')),
                ('estado', models.CharField(choices=[('1', 'Abierto'), ('0', 'Cerrado')], max_length=100, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Informe Mensual',
                'verbose_name_plural': 'Informes Mensuales',
                'db_table': 'Informe_mensual',
                'managed': True,
            },
        ),
    ]
