# Generated by Django 3.2.7 on 2022-07-06 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_congregacion', '0001_initial'),
        ('informes', '0003_alter_informemensual_año'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='informemensual',
            options={'managed': True, 'ordering': ['id'], 'verbose_name': 'Informe Mensual', 'verbose_name_plural': 'Informes Mensuales'},
        ),
        migrations.CreateModel(
            name='InformePublicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videos', models.IntegerField(blank=True, null=True)),
                ('horas', models.IntegerField(default=0)),
                ('revisitas', models.IntegerField(blank=True, null=True)),
                ('revistas', models.IntegerField(blank=True, null=True)),
                ('publicaciones', models.IntegerField(blank=True, null=True)),
                ('observaciones', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('1', 'Abierto'), ('0', 'Cerrado')], max_length=100, verbose_name='Estado')),
                ('informe_mensual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='informes.informemensual')),
                ('publicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_congregacion.publicador')),
            ],
            options={
                'verbose_name': 'Informe Publicador',
                'verbose_name_plural': 'Informes Publicador',
            },
        ),
    ]
