# Generated by Django 3.2.7 on 2022-07-06 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('informes', '0004_auto_20220705_2141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='informepublicador',
            old_name='revistas',
            new_name='cursos',
        ),
    ]
