# Generated by Django 3.2.13 on 2022-06-30 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informes', '0002_alter_informemensual_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informemensual',
            name='año',
            field=models.CharField(choices=[('1', '2022'), ('2', '2023'), ('3', '2024'), ('5', '2025')], max_length=100, verbose_name='Año'),
        ),
    ]
