# Generated by Django 4.0.6 on 2022-09-19 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informes', '0005_rename_revistas_informepublicador_cursos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='informemensual',
            options={'managed': True, 'ordering': ['id'], 'verbose_name': 'Informe Mensual', 'verbose_name_plural': 'Informe Mensual'},
        ),
        migrations.AlterField(
            model_name='informepublicador',
            name='estado',
            field=models.CharField(choices=[('1', 'Abierto'), ('0', 'Cerrado')], default='Abierto', max_length=100, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='informepublicador',
            name='observaciones',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
