# Generated by Django 4.0.6 on 2022-09-22 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('informes', '0007_año_estadoinforme_alter_informemensual_mes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='año',
            options={'managed': True, 'ordering': ['id'], 'verbose_name': 'Años', 'verbose_name_plural': 'Años'},
        ),
        migrations.AlterModelOptions(
            name='estadoinforme',
            options={'managed': True, 'ordering': ['id'], 'verbose_name': 'Estados Informes Mensuales', 'verbose_name_plural': 'Estados Informes Mensuales'},
        ),
        migrations.AlterModelTable(
            name='año',
            table='Años',
        ),
        migrations.AlterModelTable(
            name='estadoinforme',
            table='estados',
        ),
    ]
