# Generated by Django 4.0.6 on 2022-09-22 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_congregacion', '0001_initial'),
        ('informes', '0008_alter_año_options_alter_estadoinforme_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PivoteInformeMensualGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_congregacion.grupo')),
                ('informe_mensual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='informes.informemensual')),
            ],
        ),
    ]
