# Generated by Django 4.0.6 on 2022-09-29 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informes', '0009_pivoteinformemensualgrupo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='informemensual',
            options={'managed': True, 'ordering': ['-id'], 'verbose_name': 'Informe Mensual', 'verbose_name_plural': 'Informe Mensual'},
        ),
        migrations.AlterField(
            model_name='informemensual',
            name='mes',
            field=models.CharField(choices=[('Enero', 'Enero'), ('Febrero', 'Febrero'), ('Marzo', 'Marzo'), ('Abril', 'Abril'), ('Mayo', 'Mayo'), ('Junio', 'Junio'), ('Julio', 'Julio'), ('Agosto', 'Agosto'), ('Septiembre', 'Septiembre'), ('Octubre', 'Octubre'), ('Noviembre', 'Noviembre'), ('Diciembre', 'Diciembre')], max_length=100, verbose_name='Mes'),
        ),
    ]
