# Generated by Django 4.0.6 on 2022-10-07 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('informes', '0010_alter_informemensual_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UltimoInforme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('informe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='informes.informemensual')),
            ],
            options={
                'verbose_name': 'Último informe',
                'verbose_name_plural': 'Último informe',
            },
        ),
    ]
