# Generated by Django 4.0.6 on 2022-11-30 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('informes', '0013_alter_informepublicador_cursos_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PivoteUserGrupo',
        ),
    ]
