# Generated by Django 3.2.13 on 2022-06-30 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Congregacion',
            fields=[
                ('numero', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Número de congregación')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('municipio', models.CharField(max_length=200, verbose_name='Municipio o Ciudad')),
            ],
            options={
                'verbose_name': 'Congregacion',
                'verbose_name_plural': 'Congregaciones',
                'db_table': 'congregaciones',
                'ordering': ['numero'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EstadoPublicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=200, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Estado de Publicador',
                'verbose_name_plural': 'Estados de Publicadores',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('numero', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Número')),
                ('auxiliar', models.CharField(blank=True, max_length=200, null=True, verbose_name='Auxiliar')),
                ('congregacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_congregacion.congregacion')),
            ],
            options={
                'verbose_name': 'Grupo de congregación',
                'verbose_name_plural': 'Grupos de congregación',
                'db_table': 'grupos_de_congregacion',
                'ordering': ['numero'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Precursorado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precursorado', models.CharField(max_length=100, verbose_name='Precursorado')),
            ],
            options={
                'verbose_name': 'Precursorado',
                'verbose_name_plural': 'Precursorado',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Superintendente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Superintendente de grupo',
                'verbose_name_plural': 'Superintendentes de grupo',
                'db_table': 'superintendentes',
                'ordering': ['id'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tipo_publicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100, verbose_name='Tipo publicador')),
            ],
            options={
                'verbose_name': 'Tipo de publicador',
                'verbose_name_plural': 'Tipos de publicador',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Publicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='----', max_length=50, verbose_name='Sexo')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_congregacion.estadopublicador')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_congregacion.grupo')),
                ('precursor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_congregacion.precursorado')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_congregacion.tipo_publicador')),
            ],
            options={
                'verbose_name': 'Publicador',
                'verbose_name_plural': 'Publicadores',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='grupo',
            name='superintendente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_congregacion.superintendente'),
        ),
    ]
