# Generated by Django 4.0.6 on 2022-09-29 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_congregacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PivoteUserToSuperintendente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_congregacion.grupo')),
                ('superintendente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_congregacion.superintendente')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Relación Usuario a Super',
                'verbose_name_plural': 'Relación Usuario a Super',
            },
        ),
    ]
