# Generated by Django 4.0.6 on 2022-10-06 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_congregacion', '0002_pivoteusertosuperintendente'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicadorInactivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_congregacion.publicador')),
            ],
            options={
                'verbose_name': 'Publicadores inactivos',
                'verbose_name_plural': 'Publicadores inactivos',
                'ordering': ['id'],
            },
        ),
    ]
