# Generated by Django 4.0.6 on 2022-10-27 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_congregacion', '0003_publicadorinactivo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicador',
            options={'ordering': ['nombre'], 'verbose_name': 'Publicador', 'verbose_name_plural': 'Publicadores'},
        ),
        migrations.CreateModel(
            name='PublicadorIrregular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_congregacion.publicador')),
            ],
            options={
                'verbose_name': 'Publicadores irregulares',
                'verbose_name_plural': 'Publicadores irregulares',
                'ordering': ['publicador'],
            },
        ),
    ]
